#python2 deploy.py --ngpus 3 --name zhltestunet-ft-fe-pre-rgi  --repo git@github.com:lzqsd/empty.git --key siggraphasia20  python trainNetworkUnet.py --file testBRDFLocalRender.py  --flags '--cuda --isFineTuneBRDF --isBRDFFeature --isPretrained --isRandomGi --deviceIds 0 1 2 --nepoch 9'
#python2 deploy.py --ngpus 3 --name zhltestunet-ft-fe-pre-rgi-rm  --repo git@github.com:lzqsd/empty.git --key siggraphasia20  python trainNetworkUnet.py --file testBRDFLocalRender.py  --flags '--cuda --isFineTuneBRDF --isBRDFFeature --isPretrained --isRandomGi --deviceIds 0 1 2 --nepoch 9 --isRm'
#python2 deploy.py --ngpus 3 --name zhltestunet-ft-fe-pre-rgi-rll  --repo git@github.com:lzqsd/empty.git --key siggraphasia20  python trainNetworkUnet.py --file testBRDFLocalRender.py  --flags '--cuda --isFineTuneBRDF --isBRDFFeature --isPretrained --isRandomGi --deviceIds 0 1 2 --nepoch 9 --isRll'

#python2 deploy.py --ngpus 2 --name zhltestunet-gt  --repo git@github.com:lzqsd/empty.git --key siggraphasia20  python trainNetworkUnet.py --file testLocalRender.py  --flags '--cuda --deviceIds 0 1 --nepoch 7'

python2 deploy.py --ngpus 1 --name zhltestunet-ft-fe-pre-rgi  --repo git@github.com:lzqsd/empty.git --key siggraphasia20  python trainNetworkUnet.py --file testBRDFLocal.py  --flags '--cuda --isFineTuneBRDF --isBRDFFeature --isPretrained --isRandomGi --deviceIds 0 --nepoch 9'
python2 deploy.py --ngpus 1 --name zhltestunet-ft-fe-pre-rgi-rm  --repo git@github.com:lzqsd/empty.git --key siggraphasia20  python trainNetworkUnet.py --file testBRDFLocal.py  --flags '--cuda --isFineTuneBRDF --isBRDFFeature --isPretrained --isRandomGi --deviceIds 0 --nepoch 9 --isRm'
python2 deploy.py --ngpus 1 --name zhltestunet-ft-fe-pre-rgi-im  --repo git@github.com:lzqsd/empty.git --key siggraphasia20  python trainNetworkUnet.py --file testBRDFLocal.py  --flags '--cuda --isFineTuneBRDF --isBRDFFeature --isPretrained --isRandomGi --deviceIds 0 --nepoch 9 --isIm'
python2 deploy.py --ngpus 1 --name zhltestunet-ft-fe-pre-rgi-im-rm  --repo git@github.com:lzqsd/empty.git --key siggraphasia20  python trainNetworkUnet.py --file testBRDFLocal.py  --flags '--cuda --isFineTuneBRDF --isBRDFFeature --isPretrained --isRandomGi --deviceIds 0 --nepoch 9 --isRm --isIm'

python2 deploy.py --ngpus 1 --name zhltestunet-ft-pre-rgi  --repo git@github.com:lzqsd/empty.git --key siggraphasia20  python trainNetworkUnet.py --file testBRDFLocal.py  --flags '--cuda --isFineTuneBRDF --isPretrained --isRandomGi --deviceIds 0 --nepoch 9'
python2 deploy.py --ngpus 1 --name zhltestunet-ft-pre-rgi-rm  --repo git@github.com:lzqsd/empty.git --key siggraphasia20  python trainNetworkUnet.py --file testBRDFLocal.py  --flags '--cuda --isFineTuneBRDF --isPretrained --isRandomGi --deviceIds 0 --nepoch 9 --isRm'
python2 deploy.py --ngpus 1 --name zhltestunet-ft-pre-rgi-im  --repo git@github.com:lzqsd/empty.git --key siggraphasia20  python trainNetworkUnet.py --file testBRDFLocal.py  --flags '--cuda --isFineTuneBRDF --isPretrained --isRandomGi --deviceIds 0 --nepoch 9 --isIm'
python2 deploy.py --ngpus 1 --name zhltestunet-ft-pre-rgi-im-rm  --repo git@github.com:lzqsd/empty.git --key siggraphasia20  python trainNetworkUnet.py --file testBRDFLocal.py  --flags '--cuda --isFineTuneBRDF --isPretrained --isRandomGi --deviceIds 0 --nepoch 9 --isRm --isIm'
