apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ruidata-slow-vol-haosu
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Ti