apiVersion: apps/v1
kind: Deployment

metadata:
  name: ruizhu-deployment2
  namespace: ucsd-ravigroup
  labels:
    user: ruizhu

spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nginx
  template:
    metadata:
      labels:
        k8s-app: nginx
    spec:
      containers:
      - name: container
        image: localhost:30081/jerrypiglet/deeplearningconda38v5
        args: ["sleep", "infinity"]
        resources:  
          requests:
            cpu: "100m"
            memory: "100Mi"
            nvidia.com/gpu: 1
          limits:
            cpu: "16"
            memory: "16Gi"
            nvidia.com/gpu: 1
        volumeMounts:
        # - name: cephfs
        #   mountPath: /cephfs
        # - name: ruidata-fast-vol-haosu
        #   mountPath: /ruidata-fast-haosu
        # - name: ruidata-slow-vol-haosu
        #   mountPath: /ruidata-slow-haosu
        - name: dshm
          mountPath: /dev/shm
        - name: viscompfs
          mountPath: /viscompfs
        - name: eccv20dataset
          mountPath: /eccv20dataset
        - name: siggraphasia20dataset
          mountPath: /siggraphasia20dataset
        - name: ruidata
          mountPath: /ruidata

      volumes:
      # - name: cephfs
      #   persistentVolumeClaim:
      #     claimName: haosulab-cephfs
      # - name: ruidata-fast-vol-haosu
      #   persistentVolumeClaim:
      #     claimName: ruidata-fast-vol-haosu
      # - name: ruidata-slow-vol-haosu
      #   persistentVolumeClaim:
      #     claimName: ruidata-slow-vol-haosu
      - name: viscompfs
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: nautilusfs
            clusterNamespace: rook
            path: /viscompfs
            mountUser: viscompfs
            mountSecret: ceph-fs-secret
      - name: eccv20dataset
        persistentVolumeClaim:
            claimName: eccv20dataset 
      - name: siggraphasia20dataset
        persistentVolumeClaim:
            claimName: siggraphasia20dataset
      - name: ruidata
        persistentVolumeClaim:
            claimName: ruidata

      - name: dshm
        emptyDir:
          medium: Memory

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nautilus.io/group
                operator: In
                values:
                - haosu
