seed: 123
# num_gpus: 1
# num_epochs: 100
resume_dir: None
print_interval: 10

SOLVER:
  method: adam
  lr: 0.0001
  weight_decay: 0.00001
  ims_per_batch: 16

TEST:
  ims_per_batch: 16

DATASET:
  root_dir: /new_disk2/yuzh/PlaneNetData/
  # batch_size: 16
  num_workers: 16
  if_val_dist: True

MODEL_BRDF:
  load_pretrained_pth: False

MODEL_SEG:
  arch: resnet101
  pretrained: True
  embed_dims: 2
  fix_bn: False
  if_freeze: False

MODEL_SEMSEG:
  if_freeze: True
  if_guide: False
  config_file: 'configs/openrooms/openrooms_pspnet50.yaml'
  pretrained_pth: 'exp/openrooms/pspnet50V3_2gpu_100k/model/train_epoch_23_tid_147000.pth'
  
